Rewrite to check if github clone is being done before next is process

diff --git a/.github/workflows/check_plagiarism.yml b/.github/workflows/check_plagiarism.yml
--- a/.github/workflows/check_plagiarism.yml
+++ b/.github/workflows/check_plagiarism.yml
@@ -22,7 +22,12 @@ jobs:
         run: pip install compare50
 
       - name: Clone reference repository
-        run: git clone https://github.com/hackclub/sprig.git
+        run: |
+          git clone https://github.com/hackclub/sprig.git
+          if [ $? -ne 0 ]; then
+            echo "Failed to clone repository"
+            exit 1
+          fi
 
       - name: Trim JavaScript file and Check Plagiarism
         run: |
